spring:
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/ratings?authSource=admin
      database: ratings
      password: password
      username: root
  application:
    name: rating-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8083